from pydantic import BaseModel, EmailStr, Field
from typing import Optional
from datetime import datetime


class LeadBase(BaseModel):
    """Base schema for Lead creation with required fields."""
    first_name: str = Field(..., alias="Nom")
    last_name: str = Field(..., alias="Prénom")
    phone: Optional[str] = Field(None, alias="Téléphone")
    email: Optional[EmailStr] = Field(None, alias="Email")
    address: Optional[str] = Field(None, alias="Adresse")
    city: Optional[str] = Field(None, alias="Ville")
    ean_code: Optional[str] = Field(None, alias="Code EAN")
    current_provider: Optional[str] = Field(None, alias="Fournisseur actuel")
    status: Optional[str] = Field("New", alias="Statut")
    score_ia: Optional[float] = Field(None, alias="Score IA")
    last_contacted: Optional[datetime] = Field(None, alias="Dernier contact")
    next_action: Optional[str] = Field(None, alias="Prochaine action")
    date_of_birth: Optional[str] = Field(None, alias="Date de naissance")
    desire_to_change: Optional[str] = Field(None, alias="Désir de changement")
    is_eligible: Optional[bool] = Field(None, alias="Éligible")

    class Config:
        populate_by_name = True


class LeadCreate(LeadBase):
    """Schema for creating a new Lead (no lead_id, generated by Airtable)."""
    pass


class LeadReadBase(BaseModel):
    """Base schema for Lead reading (all fields optional)."""
    first_name: Optional[str] = Field(None, alias="Nom")
    last_name: Optional[str] = Field(None, alias="Prénom")
    phone: Optional[str] = Field(None, alias="Téléphone")
    email: Optional[EmailStr] = Field(None, alias="Email")
    address: Optional[str] = Field(None, alias="Adresse")
    city: Optional[str] = Field(None, alias="Ville")
    ean_code: Optional[str] = Field(None, alias="Code EAN")
    current_provider: Optional[str] = Field(None, alias="Fournisseur actuel")
    status: Optional[str] = Field("New", alias="Statut")
    score_ia: Optional[float] = Field(None, alias="Score IA")
    last_contacted: Optional[datetime] = Field(None, alias="Dernier contact")
    next_action: Optional[str] = Field(None, alias="Prochaine action")
    date_of_birth: Optional[str] = Field(None, alias="Date de naissance")
    desire_to_change: Optional[str] = Field(None, alias="Désir de changement")
    is_eligible: Optional[bool] = Field(None, alias="Éligible")

    class Config:
        populate_by_name = True


class LeadUpdate(LeadReadBase):
    """Schema for updating a Lead (all fields optional)."""
    pass


class LeadRead(LeadReadBase):
    """Schema for reading a Lead (includes lead_id from Airtable)."""
    lead_id: str
    
    class Config:
        populate_by_name = True


class Lead(LeadRead):
    """Alias for LeadRead for backward compatibility."""
    pass


class Conversation(BaseModel):
    lead_id: Optional[str]
    date: Optional[datetime]
    client_message: Optional[str]
    ai_reply: Optional[str]
    detected_intent: Optional[str]
    objection: Optional[str]
    ai_summary: Optional[str]


class Campaign(BaseModel):
    name: str
    lead_count: Optional[int]
    start_date: Optional[datetime]
    end_date: Optional[datetime]
    status: Optional[str]
